version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: php -S 0.0.0.0:3000 index.php
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    command: npm start
